version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
        default: 2.6.3
      rails_version:
        type: string
        default: 5.2.3
      project:
        type: string
      bundler_version:
        type: string
        default: '2.0.1'
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: << parameters.project >>

      - samvera/install_solr_core

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_lint_test:
          ruby_version: "2.6.3"
          rails_version: "5.2.3"
          name: "ruby2-6_rails5-2"
          project: 'hydra-pcdm'
          bundler_version: '1.17.3'
      - bundle_lint_test:
          ruby_version: "2.6.3"
          rails_version: "5.1.7"
          name: "ruby2-6_rails5-1"
          project: 'hydra-pcdm'
          bundler_version: '1.17.3'
      - bundle_lint_test:
          ruby_version: "2.5.5"
          rails_version: "5.2.3"
          name: "ruby2-5_rails5-2"
          project: 'hydra-pcdm'
          bundler_version: '1.17.3'
      - bundle_lint_test:
          ruby_version: "2.6.3"
          rails_version: "5.1.7"
          name: "ruby2-6_rails5-1"
          project: 'hydra-pcdm'
          bundler_version: '1.17.3'
      - bundle_lint_test:
          ruby_version: "2.4.6"
          rails_version: "5.2.3"
          name: "ruby2-4_rails5-2"
          project: 'hydra-pcdm'
          bundler_version: '1.17.3'
      - bundle_lint_test:
          ruby_version: "2.6.3"
          rails_version: "5.1.7"
          name: "ruby2-6_rails5-1"
          project: 'hydra-pcdm'
          bundler_version: '1.17.3'
